# Generated by Django 4.2.1 on 2023-05-30 06:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('emp_image', models.ImageField(blank=True, null=True, upload_to='upload/')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'male'), ('FEMALE', 'female')], max_length=20)),
                ('department', models.CharField(choices=[('TECHNICAL', 'technical'), ('FINANCE', 'finance'), ('ACCOUNTNT', 'accountant'), ('HR', 'hr')], default='add department', max_length=20)),
                ('designation', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('MASTER', 'master'), ('TESTER', 'tester'), ('DEVELOPER', 'developer'), ('FIELD_WORKER', 'field_worker')], max_length=20, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(choices=[('MARRIED', 'married'), ('UNMARRIED', 'unmarried')], max_length=50)),
                ('fy_year', models.CharField(choices=[('2022-2023', '2022-2023'), ('2021-2022', '2021-2022')], max_length=20)),
                ('reporting_manager_name', models.CharField(max_length=25)),
                ('holiday_leaves', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leave.holiday_leaves')),
                ('leave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leave')),
                ('leave_balance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leave_balance')),
            ],
            options={
                'db_table': 'Our_user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
