# Generated by Django 4.2.1 on 2023-05-30 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='holiday_leaves',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.holiday_leaves'),
        ),
    ]
