# Generated by Django 4.2.1 on 2023-05-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_ouruser_holiday_leaves'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouruser',
            name='date_of_joining',
        ),
    ]
