# Generated by Django 4.2.1 on 2023-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_ouruser_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='department',
            field=models.CharField(choices=[('DEVELOPMENT', 'development'), ('BACK_OFFICE', 'back_office'), ('DISPTCH', 'dispatch'), ('FIELD_ENGINEERS', 'field_engineers'), ('ACCOUNTS', 'accounts')], default='add department', max_length=20),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='role',
            field=models.CharField(choices=[('MASTER', 'master'), ('MANAGER', 'MANAGER'), ('TEAM_MEMBER', 'team_member'), ('FIELD_WORKER', 'field_worker')], max_length=20, null=True),
        ),
    ]
