# Generated by Django 4.2.1 on 2023-05-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_ouruser_department_alter_ouruser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ouruser',
            name='department',
            field=models.CharField(default='add department', max_length=20),
        ),
        migrations.AlterField(
            model_name='ouruser',
            name='role',
            field=models.CharField(choices=[('MASTER', 'master'), ('MANAGER', 'MANAGER'), ('TEAM_MEMBER', 'team_member')], max_length=20, null=True),
        ),
    ]
