# Generated by Django 4.2.1 on 2023-05-30 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='holiday_leaves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Financial_year', models.CharField(choices=[('2022-2023', '2022-2023'), ('2021-2022', '2021-2022')], max_length=20)),
                ('event_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK_LEAVE', 'sick_leave'), ('EARNED_LEAVE', 'earned_leave'), ('PRIVILAGED_LEAVE', 'privileged_leave'), ('CASUAL_LEAVE', 'casual_leave'), ('MATERNITY_LEAVE', 'maternity_leave'), ('PATERNITY_LEAVE', 'paternity_leave')], max_length=20)),
                ('reason', models.TextField(max_length=300, null=True)),
                ('date_of_leave_applied', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='leave_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leave_balance', models.IntegerField()),
                ('sick_leave_balance', models.IntegerField()),
                ('casual_leave_balance', models.IntegerField()),
                ('privilage_leave_balance', models.IntegerField()),
            ],
        ),
    ]
