# Generated by Django 4.2.1 on 2023-05-30 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='casual_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='privilage_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave',
            name='sick_leave',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='reason',
            field=models.TextField(max_length=300, null=True, verbose_name='reason of leave application'),
        ),
    ]
