# Generated by Django 4.2.1 on 2023-05-31 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leave_casual_leave_leave_privilage_leave_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='general_election',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leave_balance',
            name='paternity_leave_balance',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='leave',
            name='casual_leave',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('SICK_LEAVE', 'sick_leave'), ('EARNED_LEAVE', 'earned_leave'), ('PRIVILAGED_LEAVE', 'privileged_leave'), ('CASUAL_LEAVE', 'casual_leave'), ('MATERNITY_LEAVE', 'maternity_leave'), ('PATERNITY_LEAVE', 'paternity_leave'), ('GENERAL_ELECTION', 'general_election'), ('MATERNITY_LEAVE', 'maternity_leave')], max_length=20),
        ),
        migrations.AlterField(
            model_name='leave',
            name='privilage_leave',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leave',
            name='sick_leave',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='leave_balance',
            name='casual_leave_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leave_balance',
            name='privilage_leave_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leave_balance',
            name='sick_leave_balance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='leave_balance',
            name='total_leave_balance',
            field=models.FloatField(),
        ),
    ]
