# Generated by Django 4.2.1 on 2023-05-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leave_general_election_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='paternity_leave',
            field=models.FloatField(default=0),
        ),
    ]
